### ISSUE TITLE
As a user, I need see what i have entered for the list, so I dont enter the same thing again. 

### ISSUE THREAD

**Issue by paharisakar** [paharisakar/Recipedia#6]
- Create the list of ingredient that I have entered from the list. 
- Option to edit the list (Cross on the one corner to remove the ingredient from the list)

**Comment by zergpvz141** [comment]
Acceptance test:
* As a user, after I adding 'egg' to my search list, an oval bubble which has the word 'egg' on it appears under the search bar.
